export enum Error {
    INVALID_PARAMETER = "INVALID_PARAMETER",
    MISSING_PARAMETER = "MISSING_PARAMETER",
    ALREADY_EXIST = "ALREADY_EXIST",
    NOT_FOUND = "NOT_FOUND",
    SERVER_ERROR = "SERVER_ERROR"
}
